export const USER_ROLE = Object.freeze({
  ESTUDIANTE: 'ESTUDIANTE',
  PSICOLOGIA: 'PSICOLOGIA',
});

export const AUTH_API_ERROR = Object.freeze({
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  INVALID_RECOVERY_CODE: 'INVALID_RECOVERY_CODE',
});
