export const ADMINISTRATIVE_PAUSE_STATUS = Object.freeze({
  ACTIVA: 'ACTIVA',
  FINALIZADA: 'FINALIZADA',
  ANULADA: 'ANULADA',
});

export const ADMINISTRATIVE_PAUSE_STATUS_LABEL = Object.freeze({
  [ADMINISTRATIVE_PAUSE_STATUS.ACTIVA]: 'Activa',
  [ADMINISTRATIVE_PAUSE_STATUS.FINALIZADA]: 'Finalizada',
  [ADMINISTRATIVE_PAUSE_STATUS.ANULADA]: 'Anulada',
});
