export const PARTICIPANT_PROGRESS_STATUS = Object.freeze({
  ACTIVO: 'ACTIVO',
  EN_PAUSA: 'EN_PAUSA',
  COMPLETADO: 'COMPLETADO',
});

export const PARTICIPANT_PROGRESS_STATUS_LABEL = Object.freeze({
  [PARTICIPANT_PROGRESS_STATUS.ACTIVO]: 'Activo',
  [PARTICIPANT_PROGRESS_STATUS.EN_PAUSA]: 'En pausa',
  [PARTICIPANT_PROGRESS_STATUS.COMPLETADO]: 'Completado',
});
