export const PSYCHOEDUCATIONAL_RESOURCE_TYPE = Object.freeze({
  TEXTO: 'TEXTO',
  IMAGEN: 'IMAGEN',
  VIDEO: 'VIDEO',
  AUDIO: 'AUDIO',
  DOCUMENTO: 'DOCUMENTO',
});

export const PSYCHOEDUCATIONAL_RESOURCE_TYPE_LABEL = Object.freeze({
  [PSYCHOEDUCATIONAL_RESOURCE_TYPE.TEXTO]: 'Texto',
  [PSYCHOEDUCATIONAL_RESOURCE_TYPE.IMAGEN]: 'Imagen',
  [PSYCHOEDUCATIONAL_RESOURCE_TYPE.VIDEO]: 'Video',
  [PSYCHOEDUCATIONAL_RESOURCE_TYPE.AUDIO]: 'Audio',
  [PSYCHOEDUCATIONAL_RESOURCE_TYPE.DOCUMENTO]: 'Documento',
});

export const PSYCHOEDUCATIONAL_RESOURCE_TYPE_OPTIONS = Object.freeze([
  Object.freeze({
    value: PSYCHOEDUCATIONAL_RESOURCE_TYPE.TEXTO,
    label:
      PSYCHOEDUCATIONAL_RESOURCE_TYPE_LABEL[
        PSYCHOEDUCATIONAL_RESOURCE_TYPE.TEXTO
      ],
  }),
  Object.freeze({
    value: PSYCHOEDUCATIONAL_RESOURCE_TYPE.IMAGEN,
    label:
      PSYCHOEDUCATIONAL_RESOURCE_TYPE_LABEL[
        PSYCHOEDUCATIONAL_RESOURCE_TYPE.IMAGEN
      ],
  }),
  Object.freeze({
    value: PSYCHOEDUCATIONAL_RESOURCE_TYPE.VIDEO,
    label:
      PSYCHOEDUCATIONAL_RESOURCE_TYPE_LABEL[
        PSYCHOEDUCATIONAL_RESOURCE_TYPE.VIDEO
      ],
  }),
  Object.freeze({
    value: PSYCHOEDUCATIONAL_RESOURCE_TYPE.AUDIO,
    label:
      PSYCHOEDUCATIONAL_RESOURCE_TYPE_LABEL[
        PSYCHOEDUCATIONAL_RESOURCE_TYPE.AUDIO
      ],
  }),
  Object.freeze({
    value: PSYCHOEDUCATIONAL_RESOURCE_TYPE.DOCUMENTO,
    label:
      PSYCHOEDUCATIONAL_RESOURCE_TYPE_LABEL[
        PSYCHOEDUCATIONAL_RESOURCE_TYPE.DOCUMENTO
      ],
  }),
]);

export const PSYCHOEDUCATIONAL_FILE_RESOURCE_TYPES = Object.freeze([
  PSYCHOEDUCATIONAL_RESOURCE_TYPE.IMAGEN,
  PSYCHOEDUCATIONAL_RESOURCE_TYPE.VIDEO,
  PSYCHOEDUCATIONAL_RESOURCE_TYPE.AUDIO,
  PSYCHOEDUCATIONAL_RESOURCE_TYPE.DOCUMENTO,
]);

export const PSYCHOEDUCATIONAL_RESOURCE_FILE_ACCEPT = Object.freeze({
  [PSYCHOEDUCATIONAL_RESOURCE_TYPE.IMAGEN]: 'image/*',
  [PSYCHOEDUCATIONAL_RESOURCE_TYPE.VIDEO]: 'video/*',
  [PSYCHOEDUCATIONAL_RESOURCE_TYPE.AUDIO]: 'audio/*',
  [PSYCHOEDUCATIONAL_RESOURCE_TYPE.DOCUMENTO]: '',
});

export function isPsychoeducationalFileResourceType(type) {
  return PSYCHOEDUCATIONAL_FILE_RESOURCE_TYPES.includes(type);
}