export const TEMPORAL_UNIT_STATUS = Object.freeze({
  COMPLETADA: 'COMPLETADA',
  ACTIVA: 'ACTIVA',
  BLOQUEADA: 'BLOQUEADA',
  POR_DEFINIR: 'POR_DEFINIR',
});

export const TEMPORAL_UNIT_STATUS_LABEL = Object.freeze({
  [TEMPORAL_UNIT_STATUS.COMPLETADA]: 'Completada',
  [TEMPORAL_UNIT_STATUS.ACTIVA]: 'Activa',
  [TEMPORAL_UNIT_STATUS.BLOQUEADA]: 'Bloqueada',
  [TEMPORAL_UNIT_STATUS.POR_DEFINIR]: 'Por definir',
});

export const SCHEDULE_ACTIVATION_STATUS = Object.freeze({
  UNKNOWN: 'UNKNOWN',
  INACTIVE: 'INACTIVE',
  ACTIVE: 'ACTIVE',
});
